#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.TRecursive import fix_spec
from thrift.Thrift import TType
from thrift.transport import TTransport

all_structs = []


class CMyType(object):
    """
    Attributes:
     - buffer
     - DisabledChannels
     - StripEnableMask

    """


    def __init__(self, buffer=None, DisabledChannels=None, StripEnableMask=None,):
        self.buffer = buffer
        self.DisabledChannels = DisabledChannels
        self.StripEnableMask = StripEnableMask

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.buffer = iprot.readBinary()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.DisabledChannels = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.BYTE:
                    self.StripEnableMask = iprot.readByte()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('CMyType')
        if self.buffer is not None:
            oprot.writeFieldBegin('buffer', TType.STRING, 1)
            oprot.writeBinary(self.buffer)
            oprot.writeFieldEnd()
        if self.DisabledChannels is not None:
            oprot.writeFieldBegin('DisabledChannels', TType.I32, 2)
            oprot.writeI32(self.DisabledChannels)
            oprot.writeFieldEnd()
        if self.StripEnableMask is not None:
            oprot.writeFieldBegin('StripEnableMask', TType.BYTE, 3)
            oprot.writeByte(self.StripEnableMask)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(CMyType)
CMyType.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'buffer', 'BINARY', None, ),  # 1
    (2, TType.I32, 'DisabledChannels', None, None, ),  # 2
    (3, TType.BYTE, 'StripEnableMask', None, None, ),  # 3
)
fix_spec(all_structs)
del all_structs
