/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MyType_constants.h"

namespace sonicationhal_thrift {

const MyTypeConstants g_MyType_constants;

MyTypeConstants::MyTypeConstants() {
}

} // namespace

