/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftDemoInterface_constants.h"

namespace demo_thrift {

const ThriftDemoInterfaceConstants g_ThriftDemoInterface_constants;

ThriftDemoInterfaceConstants::ThriftDemoInterfaceConstants() {
}

} // namespace

