/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MyType_CONSTANTS_H
#define MyType_CONSTANTS_H

#include "MyType_types.h"

namespace sonicationhal_thrift {

class MyTypeConstants {
 public:
  MyTypeConstants();

};

extern const MyTypeConstants g_MyType_constants;

} // namespace

#endif
