/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftDemoInterface_CONSTANTS_H
#define ThriftDemoInterface_CONSTANTS_H

#include "ThriftDemoInterface_types.h"

namespace demo_thrift {

class ThriftDemoInterfaceConstants {
 public:
  ThriftDemoInterfaceConstants();

};

extern const ThriftDemoInterfaceConstants g_ThriftDemoInterface_constants;

} // namespace

#endif
